#!/bin/bash
gcc main.c LemonMain.c gameObjects.c fileLoader.c drawScreen.c playerController.c spriteLoader.c soundProcessor.c eventManager.c animations.c UIObjects.c textHandler.c cutsceneManager.c console.c -o stable/LemonEngine_Linux `pkg-config --libs --cflags sdl3` -L./stable -lSDL3_image -lSDL3_ttf -lSDL3_mixer -O3 -m64 -lm --all-warnings
